#!/usr/bin/bash

# SET MONITOR PREFERENCES
# -----------------------
	# Set Gaming Workspace
	CONFIG="$HOME/.config/hypr/UserConfigs/WindowRules.conf"
	sed -i -E "/windowrulev2 = workspace (8|9), tag:games\*/d" "$CONFIG"
	echo "windowrulev2 = workspace 8, tag:games*" >> "$CONFIG"
	# Set DP-3 as primary monitor
	xrandr --output DP-3 --primary
	# Reload Hyprland configuration
	hyprctl reload
# -----------------------

# SET ENV Variables
# -----------------

	# Monitor DP-3 settings
	export DXVK_ASYNC=1                             # DXVK_ASYNC
	export __GL_GSYNC_ALLOWED=0                     # Controls if G-Sync capable monitors should use Variable Refresh Rate (VRR)
	export __GL_VRR_ALLOWED=0                       # Controls if Adaptive Sync should be used. Recommended to set as “0” to avoid having problems on some games.
	export __GL_SYNC_TO_VBLANK=0                    # used to control whether swaps are synchronized to a display device's vertical refresh.
	export __GL_SYNC_DISPLAY_DEVICE=DP-3            # specify to which display device OpenGL should sync	

	# General Settings
	export WLR_DRM_NO_ATOMIC=1                      # Disable vsync and allow tearing (reduces input lag)
	export WLR_NO_HARDWARE_CURSORS=1                # Fix cursor corruption in some games 
	export DXVK_STATE_CACHE=1                       # reduces stutter by caching shaders
	export __GL_SHADER_DISK_CACHE=1                 # reduces stutter by caching shaders
	export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1    # reduces stutter by caching shaders
	export __GL_SHADER_DISK_CACHE_SIZE=100000000000 # reduces stutter by caching shaders
	export __GL_YIELD=USLEEP                        # helps with CPU-bound scenarios
	export __GL_MaxFramesAllowed=1                  # reduces input lag
	export __GL_SHOW_GRAPHICS_OSD=0                 # Disable NVIDIA's Debug Warnings - Reduces log spam 
	export __GL_PERSISTENT_DISPLAY_PRIORITY=1       # prevents GPU from downclocking during lighter loads
	export NVIDIA_REFRESH_RATE=120                  # NVIDIA Reflex Support (Reduces latency further)
	export LD_PRELOAD=""                            # reduces stutter

	# DLSS Settings
	export PROTON_ENABLE_NVAPI=1                    # Enable DLSS
	export PROTON_ENABLE_NGX_UPDATER=1              # Force DLSS Update
	# Enable Latest DLSS version
	export DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE=on
	export DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE=on
	export DXVK_NVAPI_DRS_NGX_DLSS_FG_OVERRIDE=on
	export DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE_RENDER_PRESET_SELECTION=render_preset_latest
	export DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE_RENDER_PRESET_SELECTION=render_preset_latest
	export DXVK_NVAPI_SET_NGX_DEBUG_OPTIONS=DLSSIndicator=0,DLSSGIndicator=0      # Disable DLSS Indicator
	#export DXVK_NVAPI_SET_NGX_DEBUG_OPTIONS=DLSSIndicator=1024,DLSSGIndicator=2  # Enable DLSS Indicator
	
	# Documentation
	# - https://github.com/jp7677/dxvk-nvapi
	# - https://download.nvidia.com/XFree86/Linux-32bit-ARM/375.26/README/openglenvvariables.html
	
# -----------------

# applied variables, now execute the rest of the command
exec "$@"
